### ISSUE TITLE
Build issues on Ubuntu Description:    Ubuntu 12.04.2 LTS Release:        12.04 Codename:       precise

### ISSUE THREAD

**Issue by ghost** [mscdex/pmq#1]
Needs {} on constructor to compile on Ubuntu.

```
PosixMQ() : mqpollhandle(NULL), mqdes(MQDES_INVALID), mqname(NULL),
            canread(false), canwrite(false) {};
```

 node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@0.10.0
gyp info using node@0.10.12 | linux | x64
gyp info spawn python
gyp info spawn args [ '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ubuntu/build/pmq/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ubuntu/.node-gyp/0.10.12/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/ubuntu/.node-gyp/0.10.12',
gyp info spawn args   '-Dmodule_root_dir=/home/ubuntu/build/pmq',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/home/ubuntu/build/pmq/build'
  CXX(target) Release/obj.target/posixmq/src/posixmq.o
../src/posixmq.cc: In constructor â:
../src/posixmq.cc:31:16: warning: â will be initialized after [-Wreorder]
../src/posixmq.cc:29:11: warning:   â [-Wreorder]
../src/posixmq.cc:37:5: warning:   when initialized here [-Wreorder]
../src/posixmq.cc:38:47: error: expected â at end of input
make: *** [Release/obj.target/posixmq/src/posixmq.o] Error 1
make: Leaving directory`/home/ubuntu/build/pmq/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Linux 3.2.0-49-virtual
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ubuntu/build/pmq
gyp ERR! node -v v0.10.12
gyp ERR! node-gyp -v v0.10.0
gyp ERR! not ok

**Comment by mscdex** [comment]
I'd accept a PR for this.
